### Get offer by id
GET http://localhost:8080/api/offer/{id}

### Add new offer for author
POST http://localhost:8080/api/offer/create
Content-Type: application/json

{
  "title": "nowa oferta",
  "description": "good job",
  "employerId": 1
}

### Get employer by id
GET http://localhost:8080/api/employer/{id}

### Create employer
POST http://localhost:8080/api/employer
Content-Type: application/json

{
  "name": "TestCompany",
  "description": "hehehee"
}

###Jobs Filtering

### Get filter on location
GET http://localhost:8080/api/filterOffers/location

### Get filter on experiencelevel
GET http://localhost:8080/api/filterOffers/experienceLevel

### Get filter on role
GET http://localhost:8080/api/filterOffers/roles

### Get filter on employmentModel
GET http://localhost:8080/api/filterOffers/employmentModel

### Get filter on employmentType
GET http://localhost:8080/api/filterOffers/employmentType

### Get categoryNameAndCount
GET http://localhost:8080/api/filterOffers/categoryNameAndCount

### Get jobs of the day
GET http://localhost:8080/api/filterOffers/jobsOfTheDay

### Get count on all
GET http://localhost:8080/api/filterOffers/all

### Get rowJobOfferList
GET http://localhost:8080/api/filterOffers/rowJobOfferList

### Get country box list
GET http://localhost:8080/api/filterOffers/countryBoxList

### Get jobs by categoryName
GET http://localhost:8080/api/filterOffers/jobsListByCategory/{categoryName}

### Get similar jobs
GET http://localhost:8080/api/filterOffers/similarJobs/DEVOPS

### Get jobs from the same employer
GET http://localhost:8080/api/filterOffers/jobsByTheSameEmployer/1

### Get filtered offers by offer id
GET http://localhost:8080/api/filterOffers/1

###Employers

### Get industry box list
GET http://localhost:8080/api/filterEmployer/industryBoxList

### Get country box list
GET http://localhost:8080/api/filterEmployer/countryBoxList

### Get all filtred employers
GET http://localhost:8080/api/filterEmployer/all

### Filter frontEndEmployerByid
GET http://localhost:8080/api/filterEmployer/byId/1