### Get all offers
GET http://localhost:8080/api/offer

### Get offer by id
GET http://localhost:8080/api/offer/1

### Add new offer for author
POST http://localhost:8080/api/offer/create
Content-Type: application/json

{
  "title": "nowa oferta",
  "description": "good job",
  "employerId": 1
}

### Get all employers
GET http://localhost:8080/api/employer

### Get employer by id
GET http://localhost:8080/api/employer/1

### Create employer
POST http://localhost:8080/api/employer
Content-Type: application/json

{
  "name": "TestCompany",
  "description": "hehehee"
}
