version: '3.8'

services:
  my-postgres-db:
    image: postgres:latest
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5439:5432"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
